import '@fontsource/lexend/100.css'
import '@fontsource/lexend/200.css'
import '@fontsource/lexend/300.css'
import '@fontsource/lexend/400.css'
import '@fontsource/lexend/500.css'
import '@fontsource/lexend/600.css'
import '@fontsource/lexend/700.css'
import '@fontsource/lexend/900.css'
